In [6]:
import pandas as pd
df = pd.read_excel(r'C:\Users\zqy\Desktop\来源去向.xlsx',sheet_name = 'Sheet2')
import re
df = df.applymap(lambda x:re.sub('nan','',str(x)))
bd = pd.melt(df, id_vars = df.columns.to_list()[0:10],value_vars = df.columns.to_list()[10:], var_name='type',value_name='value')
bd_1 = bd['type'].str.split('&',expand = True)
df_1 = pd.merge(bd,bd_1,how = 'left',left_index = True ,right_index = True)
df_1.drop(df_1[df_1['value']==''].index,axis = 0).to_excel(r'C:\Users\zqy\Desktop\转置完来源去向.xlsx',index = None)

In [7]:
df_店 = pd.read_excel(r'C:\Users\zqy\Desktop\转置完.xlsx',dtype = object)
df_店 = df_店.applymap(lambda x:re.sub('nan','',str(x)))
df_店['对手方向'] = df_店['12月&时间&事项'].map(lambda x : '出' if x == '入' else '入')
df_店['左']= df_店['对手方向']+df_店['type']

df_店

,银行,编号,名字,结余,帐户余额,实际余额,备注,查询日,银行总扣费,12月&时间&事项,type,value,0,1,2,3,对手方向,左
0,1店,HK,现金,50378850,30536960,,,,,入,1&0:12:00&9过1&1,287750.0,1,0:12:00,9过1,1,出,出1&0:12:00&9过1&1
1,9店,HK,现金,6530410,878080,,,,,出,1&0:12:00&9过1&1,287750.0,1,0:12:00,9过1,1,入,入1&0:12:00&9过1&1
2,1店,HK,现金,50378850,30536960,,,,,入,1&0:14:00&9过1&2,2112250.0,1,0:14:00,9过1,2,出,出1&0:14:00&9过1&2
3,9店,HK,现金,6530410,878080,,,,,出,1&0:14:00&9过1&2,2112250.0,1,0:14:00,9过1,2,入,入1&0:14:00&9过1&2
4,1店,HK,现金,50378850,30536960,,,,,入,1&13:35:00&2过1&3,5500000.0,1,13:35:00,2过1,3,出,出1&13:35:00&2过1&3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11622,9店,HK,现金,6530410,878080,,,,,出,31&23:13:00&&10768,300990.0,31,23:13:00,,10768,入,入31&23:13:00&&10768
11623,9店,HK,现金,6530410,878080,,,,,出,31&23:29:00&&10769,190630.0,31,23:29:00,,10769,入,入31&23:29:00&&10769
11624,9店,HK,现金,6530410,878080,,,,,入,31&23:24:00&&10770,30000.0,31,23:24:00,,10770,出,出31&23:24:00&&10770
11625,9店,HK,现金,6530410,878080,,,,,入,31&23:53:00&&10771,100000.0,31,23:53:00,,10771,出,出31&23:53:00&&10771
11626,9店,HK,现金,6530410,878080,,,,,入,31&22:51:00&&10772,149500.0,31,22:51:00,,10772,出,出31&22:51:00&&10772

In [9]:
df_对手 = df_1.drop(df_1[df_1['value']==''].index,axis = 0)
df_对手['右']= df_对手['12月&时间&事项']+df_对手['type']
df_对手

,银行,编号,名字,结余,12月&时间&事项,1&0:12:00&9过1&1,1&0:14:00&9过1&2,1&13:35:00&2过1&3,1&14:41:00&1过9&4,1&15:30:00&1过9&5,type,value,0,1,2,3,右
314,卡机,D12-1,天赠中行,-345061,出,,,,,,1&15:47:00&&6,103522.0,1,15:47:00,,6,出1&15:47:00&&6
608,卡机,O1-3,亮有建行,78,出,,,,,,1&15:47:00&&6,1000000.0,1,15:47:00,,6,出1&15:47:00&&6
8405,卡机,D5-1,松晔中行,-345065,入,,,,,,1&13:14:00&&17,500000.0,1,13:14:00,,17,入1&13:14:00&&17
8407,卡机,D8-6,文祥平安,94,入,,,,,,1&13:14:00&&17,2050000.0,1,13:14:00,,17,入1&13:14:00&&17
8411,卡机,D12-1,天赠中行,-345061,入,,,,,,1&13:14:00&&17,500000.0,1,13:14:00,,17,入1&13:14:00&&17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7925872,卡机,O3-1,永高中行,2,出,,,,,,31&31/12，16:30～17:10&支付11月份pos机佣金&10774,358419.0,31,31/12，16:30～17:10,支付11月份pos机佣金,10774,出31&31/12，16:30～17:10&支付11月份pos机佣金&10774
7925936,卡机,P2-4,冉燕农行,5,出,,,,,,31&31/12，16:30～17:10&支付11月份pos机佣金&10774,262469.0,31,31/12，16:30～17:10,支付11月份pos机佣金,10774,出31&31/12，16:30～17:10&支付11月份pos机佣金&10774
7926090,卡机,360-2,清土民生,188,出,,,,,,31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775,19569.0,31,31/12，16:30～17:10,支付11月份汇入户口佣金,10775,出31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775
7926172,卡机,756-3,诗纺建行,2,出,,,,,,31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775,40670.0,31,31/12，16:30～17:10,支付11月份汇入户口佣金,10775,出31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775
7926592,卡机,O1-3,亮有建行,78,出,,,,,,31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775,93864.0,31,31/12，16:30～17:10,支付11月份汇入户口佣金,10775,出31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775

In [10]:
df_本方对手 = pd.merge(df_店,df_对手,how = 'right',left_on = '左' ,right_on = '右')

In [11]:
df_本方对手.to_excel(r'C:\Users\zqy\Desktop\本方来源去向.xlsx',index = None)
df_本方对手

,银行_x,编号_x,名字_x,结余_x,帐户余额,实际余额,备注,查询日,银行总扣费,12月&时间&事项_x,...,1&13:35:00&2过1&3,1&14:41:00&1过9&4,1&15:30:00&1过9&5,type_y,value_y,0_y,1_y,2_y,3_y,右
0,1店,HK,现金,50378850,30536960,,,,,入,...,,,,1&15:47:00&&6,103522.0,1,15:47:00,,6,出1&15:47:00&&6
1,1店,HK,现金,50378850,30536960,,,,,入,...,,,,1&15:47:00&&6,1000000.0,1,15:47:00,,6,出1&15:47:00&&6
2,1店,HK,现金,50378850,30536960,,,,,出,...,,,,1&13:14:00&&17,500000.0,1,13:14:00,,17,入1&13:14:00&&17
3,1店,HK,现金,50378850,30536960,,,,,出,...,,,,1&13:14:00&&17,2050000.0,1,13:14:00,,17,入1&13:14:00&&17
4,1店,HK,现金,50378850,30536960,,,,,出,...,,,,1&13:14:00&&17,500000.0,1,13:14:00,,17,入1&13:14:00&&17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,31&31/12，16:30～17:10&支付11月份pos机佣金&10774,358419.0,31,31/12，16:30～17:10,支付11月份pos机佣金,10774,出31&31/12，16:30～17:10&支付11月份pos机佣金&10774
13622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,31&31/12，16:30～17:10&支付11月份pos机佣金&10774,262469.0,31,31/12，16:30～17:10,支付11月份pos机佣金,10774,出31&31/12，16:30～17:10&支付11月份pos机佣金&10774
13623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775,19569.0,31,31/12，16:30～17:10,支付11月份汇入户口佣金,10775,出31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775
13624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775,40670.0,31,31/12，16:30～17:10,支付11月份汇入户口佣金,10775,出31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775
13625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775,93864.0,31,31/12，16:30～17:10,支付11月份汇入户口佣金,10775,出31&31/12，16:30～17:10&支付11月份汇入户口佣金&10775